name: Publish to npm

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version type to update (major, minor, patch, prerelease)"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Update version
        env:
          TOKEN: ${{ secrets.FORCE_PUSH_TOKEN }}
        run: |
          npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "chore(release): bump version to $(node -p "require('./package.json').version")"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD

      - name: Build project
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci && npm publish --access public
